[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LTWaffles86", email = "hl1254@scarletmail.rutgers.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pathlib>=1.0.1",
    "pillow>=12.3.0",
]

[project.scripts]
code = "code:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ty>=0.0.84",
]
